name: 'Get Contract Language Version'
description: 'Checks if all contracts have the same language version.'

inputs:
  contracts-directory:
    description: 'Path to the directory containing contracts.'
    required: true
outputs:
  language:
    description: "Language version"
    value: ${{ steps.language.outputs.language }}

runs:
  using: 'composite'
  steps:
    - name: Check contract language version
      id: language
      run: |
        language=""
        # Iterate over each contract in the directory
        for contract in "${{ inputs.contracts-directory }}"/*.contract; do
          current_language=$(jq -r '.source.language' "$contract")

          # Check if the current language is different from the previous one
          if [ -n "$language" ] && [ "$current_language" != "$language" ]; then
            echo "Error: Different language detected in contract $contract: $language != $current_language"
            exit 1
          fi

          language="$current_language"

          echo "Contract: $contract, Language: $current_language"
        done
        echo "language=$language" >> $GITHUB_OUTPUT
      shell: bash
