name: Build examples

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  quick_check:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src

      - name: Cache Dependencies & Build Outputs
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v3.0.11
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f #v1.3.0
        with:
          crate: cargo-dylint

      - name: Install dylint-link
        uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f #v1.3.0
        with:
          crate: dylint-link

      - name: Install cargo-contract
        uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f #v1.3.0
        with:
          crate: cargo-contract
          version: "2.0.0-rc"

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install cargo-contract and build contract
        shell: bash
        run: |
          git clone --verbose --depth 1 https://github.com/paritytech/ink.git
          mv Cargo.toml _Cargo.toml
          ./scripts/ci/build-contract.sh ./ink/integration-tests/public/erc20
          mv _Cargo.toml Cargo.toml
